### ISSUE TITLE
how to deal with this bug? --No module named 'lib.utils.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by liye228** [ShuangXieIrene/ssds.pytorch#10]
from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'lib.utils.nms._ext.nms._nms'

I use python3.6 .

**Comment by foreverYoungGitHub** [comment]
It is caused by the nms implementation with cuda version. We should remove it from the newest, please pull the newest version first.

But if you still have this problem. There are two solutions. 1) try to remove all the lib.utils.nms from your python file, or 2) try to build the cuda version nms based on the `make.sh` in `lib/utils/nms`
