### ISSUE TITLE
ImportError: No module named _mask

### ISSUE THREAD

**Issue by isalirezag** [ShuangXieIrene/ssds.pytorch#22]
I run this code `python train.py --cfg=./experiments/cfgs/ssd_vgg16_train_voc.yml` and this is what i get:
```
python train.py --cfg=./experiments/cfgs/ssd_vgg16_train_voc.yml
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from lib.ssds_train import train_model
  File "/home/alireza/Desktop/ssd/B/lib/ssds_train.py", line 23, in <module>
    from lib.dataset.dataset_factory import load_data
  File "/home/alireza/Desktop/ssd/B/lib/dataset/dataset_factory.py", line 2, in <module>
    from lib.dataset import coco
  File "/home/alireza/Desktop/ssd/B/lib/dataset/coco.py", line 13, in <module>
    from lib.utils.pycocotools.coco import COCO
  File "/home/alireza/Desktop/ssd/B/lib/utils/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/alireza/Desktop/ssd/B/lib/utils/pycocotools/mask.py", line 3, in <module>
    import lib.utils.pycocotools._mask as _mask
ImportError: No module named _mask
```

Any idea why??
Also What python version are using?
Plut where should i put the dataset (eg coco vgg)

**Comment by isalirezag** [comment]
I was using python 2 and that was the issue...

**Comment by ramonidea** [comment]
What was your solution to this?

**Comment by isalirezag** [comment]
switch to python 3

**Comment by vaishnavm217** [comment]
I am getting the same error in my gpu server, although it worked in my pc

**Comment by seongkyun** [comment]
I have solved this problem without any upgrading python version.
My python version is Python 3.5.
The problem is just 
`/home/username/study/tl_ssd_2/lib/utils/pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so`
file.
Just install COCOAPI following https://github.com/cocodataset/cocoapi instruction
and copy and paste `_mask.cpython-**YOUR_PYTHON_VERSION**m-x86_64-linux-gnu.so` file to 
`/home/username/study/tl_ssd_2/lib/utils/pycocotools`

then the error will be dissappeared.

**Comment by stalagmite7** [comment]
where is this file? I cant find it after install cocoapi.

**Comment by seongkyun** [comment]
@stalagmite7 
You can find that folder at `your_dir/cocoapi/PythonAPI/pycocotools`
