### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ParusMajor60** [ShuangXieIrene/ssds.pytorch#50]
Hi,

I'm trying to do a test for the ssd_vgg model on VOC dataset, but I'm getting the following error : 

Segmentation fault (core dumped)

I was using Python3.6 and Pytorch 0.4.1, after seeing this error I switched back to Pytorch 0.4.0. But the error is still there. 

The command I run is:
python test.py --cfg=./experiments/cfgs/ssd_vgg16_train_voc.yml  

I have changed the corresponding directories and weights in the yml file to be those I need.

Any help would be more than appreciated.
Thanks in advance!

**Comment by QZ-cmd** [comment]
hello，can you tell me how to solve this problem，i have a same problem... thanks

**Comment by foreverYoungGitHub** [comment]
@QZ-cmd @ParusMajor60 
Please try the newest pytorch version (1.5) with dev branch and check whether the problem still existed. Also it is good to attach the detail log for better debugging.

**Comment by QZ-cmd** [comment]
> @QZ-cmd @ParusMajor60
> Please try the newest pytorch version (1.5) with dev branch and check whether the problem still existed. Also it is good to attach the detail log for better debugging.

Thank you for your reply，i change :  images = torch.Tensor(images).to(self.device) -> images = images.to(self.device)  in yolov2_test_model.py solve this problem,but I don't know what the negative impact will be，Look forward to your reply

**Comment by foreverYoungGitHub** [comment]
Based on the given code, the `images = torch.Tensor(images).to(self.device)` expect for the numpy.ndarray input and transfer it to the torch.Tensor, while `images = images.to(self.device)` seems already get the torch.Tensor for `images`. Since I'm not so sure where does the yolov2_test_model.py script come from. So not so sure about the potential issue for that script.

Btw, welcome to try the new 1.5 version for ssds.pytorch. I'm working on the document in the recent days and it is available at https://foreveryounggithub.github.io/ssds.doc/
